### ISSUE TITLE
Is it possible for the cards to be angled by default?

### ISSUE THREAD

**Issue by Androneilz** [BakerJQ/InfiniteCards#10]
Apologies that this isn't an issue, but maybe you can advise how this can be done.

Do you think it's possible to have the cards angled slightly by default, as they appear in this example:

https://uimovement.com/ui/3782/credit-card/

Thanks for looking.

**Comment by BakerJQ** [comment]
Yes it's possible, just set the rotateX value.

**Comment by Androneilz** [comment]
Thank you! After some experimentation that has worked perfectly.

One final question. Bearing in mind my cards are now angled slightly, with padding around them, I'd like to create an additional animation to which moves the card at the front of the stack to a full width, flat position. Please see screenshots for examples of the start and finish positions. I'd also want to reverse the animation to return the selected card back into the angled stack.

Is this something you are able to help with?

![device-2017-10-08-162345](https://user-images.githubusercontent.com/32375009/31318147-702b8824-ac45-11e7-8e52-9046bf747135.png)

![device-2017-10-08-162431](https://user-images.githubusercontent.com/32375009/31318153-7a915a8c-ac45-11e7-8504-d91617cb0e01.png)

**Comment by BakerJQ** [comment]
maybe you'll need to rewrite the other transformers too

**Comment by Androneilz** [comment]
Yes, I think I've achieved what I wanted. Thanks again for the great library!

**Comment by BakerJQ** [comment]
My pleasure ：)
