### ISSUE TITLE
only show one card to view 

### ISSUE THREAD

**Issue by o0ohh** [BakerJQ/InfiniteCards#11]
How can I only show one card to view,, and the others hidden?

**Comment by BakerJQ** [comment]
Why would you need to do so？Just one card？
You can try make the resId array in MainActivity contains only one id, like only pic1, but in this case, other switching methods are useless.

**Comment by o0ohh** [comment]
我的意思是我的resId array有多个View，但是我只想把最前面的那个显示出来，其他的隐藏，因为我用的不是图片而是有字的view，不设置背景色的话后面view也会看到导致字重叠，设置背景颜色的话又会遮挡根layout的背景图片。。。
