### ISSUE TITLE
java.lang.NullPointerException:

### ISSUE THREAD

**Issue by piyushmishra10** [BakerJQ/InfiniteCards#12]
Attempt to invoke virtual method 'int android.widget.BaseAdapter.getCount()' on a null object reference

 private void firstSetAdapter(BaseAdapter adapter) {
        if (mTransformerAnimAdd != null) {
            mIsAddRemoveAnim = true;
        }
        mCards = new LinkedList<>();
//            mCards4JudgeZIndex = new ArrayList<>();
        mCardCount = adapter.getCount(); (issue)

It's leading me to your firstSetAdapter. Tried many times other infinite views are working properly but after many attempts, your code is crashing on CardAnimationHelper class line 463.

**Comment by Chaosxing** [comment]
This method begins when the page created.
This means you have to set a default and not empty BaseAdapter
```
mAdapter.registerDataSetObserver(new DataSetObserver(){
  Public void onChanged(){
    mAnimationHelper.notifyDataSetChanged(mAdapter);
  }
});
```
Although I found this in the code, I still did not change the data when BaseAdapter.notifyDataSetChanged. The author seems to have not updated for a long time. I am looking for the cause of the problem myself.
