### ISSUE TITLE
Can I implement swipe action on the items.

### ISSUE THREAD

**Issue by AtharvaAbsolute** [BakerJQ/InfiniteCards#14]
My items have click listeners embedded in them, so I want the cards to change on swipe instead of a click action. Is the functionality available in the current version?

**Comment by BakerJQ** [comment]
It is not support for swipe actions, but you can implement it by extending InfiniteCardView and override onTouch method

**Comment by AtharvaAbsolute** [comment]
I have integrated the library pretty good, it has solved 90% of my problem, the only issue I'm facing is that the swipe actions that I'm using by overriding the onTouchListener is working outside the bounds of the component and not on the card, I have put the listener on the library component.

**Comment by AtharvaAbsolute** [comment]
Is there any way I can implement swipe actions on the child view, my adapter item.

**Comment by BakerJQ** [comment]
Maybe you can try intercepting touch event on your adapter item

**Comment by AtharvaAbsolute** [comment]
Yeah, I did that, it worked. Thanks!.

**Comment by AtharvaAbsolute** [comment]
![Screenshot from 2019-03-18 02-01-01](https://user-images.githubusercontent.com/19706447/54509925-b6bb7e00-4921-11e9-996e-e95cc79621e2.png)

My current layout is currently like as shown in 1, but I want it to be like 2, can this be done. Can I set any offset or something.

**Comment by BakerJQ** [comment]
This can be done by recalculating in AnimationTransformer, as shown in the customisation section (https://github.com/BakerJQ/Android-InfiniteCards#customisation) , you may try add setTranslationX

**Comment by AtharvaAbsolute** [comment]
I want to show an automatic demo swipe every time my app launches. I'm currently using the following code:

`cardStackView.bringCardToFront(1);`

Error:

` Attempt to invoke virtual method 'java.lang.Object java.util.LinkedList.getFirst()' on a null object reference
        at com.bakerj.infinitecards.CardAnimationHelper.bringCardToFront(CardAnimationHelper.java:587)
        at com.bakerj.infinitecards.InfiniteCardView.bringCardToFront(InfiniteCardView.java:159)`

**Comment by BakerJQ** [comment]
The list is not created yet, maybe you should do this after the view is fully attached

**Comment by AtharvaAbsolute** [comment]
I'm calling this in `onViewCreated()`

**Comment by BakerJQ** [comment]
The list is set after getting exact width and height in onMeasure

**Comment by AtharvaAbsolute** [comment]
Thanks, I did it.
