### ISSUE TITLE
Show selected items from list on the view

### ISSUE THREAD

**Issue by AtharvaAbsolute** [BakerJQ/InfiniteCards#15]
I have two items in my adapter, let's assume that there are two credit cards there on the view, one of them is activated and one is not, so I want the activated one to show on the front and the inactive to go in the back.
![Screenshot from 2019-03-28 07-42-28](https://user-images.githubusercontent.com/19706447/55155167-15a4a280-512d-11e9-8587-26afc9912fa9.png).

**Comment by BakerJQ** [comment]
Maybe you should implement this by control the order of your item in the item list.
