### ISSUE TITLE
View taking padding by default

### ISSUE THREAD

**Issue by AtharvaAbsolute** [BakerJQ/InfiniteCards#16]
I have implemented the view successfully and everything is working fine except that it takes additional padding and appears to be very small on high DPI devices.

**Comment by BakerJQ** [comment]
Any screenshots?

**Comment by AtharvaAbsolute** [comment]
I cannot share screenshots with you but can give you a visual representation of the issue.
![Screenshot from 2019-04-04 01-30-02](https://user-images.githubusercontent.com/19706447/55531670-36af4b00-5679-11e9-90c6-843b494e2a7d.png)

**Comment by BakerJQ** [comment]
This is because the original code has a scale effect, which may makes the padding bigger in high dpi devices, you may implement the transforms in your own way to solve this problem

**Comment by AtharvaAbsolute** [comment]
Okay, will try it, thanks!

**Comment by AtharvaAbsolute** [comment]
It worked thanks!
