### ISSUE TITLE
Delay in swap animation due to late UI rendering.

### ISSUE THREAD

**Issue by AtharvaAbsolute** [BakerJQ/InfiniteCards#17]
Hi, I'm facing some issues with the swap animation. My adapter earlier was very long and inefficient so I had to put 1.5s delay so that the cards UI can render properly and then the swap animation took place. Now I have optimized the adapter to an extent where it can't be optimized more I guess and I see a much better performance boost. I have written all the necessary cases for the adapter in my model class and the adapter has just got to render the UI and nothing else, no complex conditions are present. But I'm still facing that issue even after such a fast operation, the swap animation doesn't work if I remove the delay or decrease it lesser than 1500ms. I'm using a Handler for this. Can you give me some insight into how can I lower the delay?. Thanks

**Comment by BakerJQ** [comment]
If you can give a demo code to me, maybe I can understand the situation better. For now, I don't quite understand the situation you described

**Comment by AtharvaAbsolute** [comment]
[card.txt](https://github.com/BakerJQ/Android-InfiniteCards/files/3425349/card.txt)
Please check this file out, I can't share the adapter with you due to security concerns. I'll walk you through the code, can you set up a call if possible? Thanks.

**Comment by BakerJQ** [comment]
Did you do any operation on setTransformerAnimAdd

**Comment by AtharvaAbsolute** [comment]
I'm using this function for animation:
`private void setStyle3() {
        cardStackView.setClickable(false);
        cardStackView.setAnimType(InfiniteCardView.ANIM_TYPE_SWITCH);
        cardStackView.setAnimInterpolator(new OvershootInterpolator(-8));
        cardStackView.setTransformerToFront(new DefaultCommonTransformer());
        cardStackView.setTransformerToBack(new AnimationTransformer() {
            @Override
            public void transformAnimation(View view, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {
                int positionCount = fromPosition - toPosition;
                float scale = (0.8f - 0.1f * fromPosition) + (0.1f * fraction * positionCount);
                view.setScaleX(scale);
                view.setScaleY(scale);
                if (fraction < 0.5) {
                    view.setTranslationX(cardWidth * fraction * 1.5f);
                    view.setRotationY(-45 * fraction);
                } else {
                    view.setTranslationX(cardWidth * 1.5f * (1f - fraction));
                    view.setRotationY(-45 * (1 - fraction));
                }
            }

            @Override
            public void transformInterpolatedAnimation(View view, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {
                int positionCount = fromPosition - toPosition;
                float scale = (0.8f - 0.1f * fromPosition) + (0.1f * fraction * positionCount);
                view.setTranslationY(-cardHeight * (0.8f - scale) * 0.5f - cardWidth * (0.02f *
                        fromPosition - 0.02f * fraction * positionCount));
            }
        });
        cardStackView.setZIndexTransformerToBack(new ZIndexTransformer() {
            @Override
            public void transformAnimation(CardItem card, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {
                if (fraction < 0.5f) {
                    card.zIndex = 1f + 0.01f * fromPosition;
                } else {
                    card.zIndex = 1f + 0.01f * toPosition;
                }
            }

            @Override
            public void transformInterpolatedAnimation(CardItem card, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {

            }
        });
    }`

**Comment by AtharvaAbsolute** [comment]
[https://pastebin.com/i1LMSLYV](url)
I'm using this function for animation.

**Comment by BakerJQ** [comment]
Maybe you can try setTransformerAnimAdd(null) and setTransformerAnimRemove(null) then remove the delay

**Comment by AtharvaAbsolute** [comment]
And where do I do this?

**Comment by BakerJQ** [comment]
Just after initiate eg. findViewById

**Comment by AtharvaAbsolute** [comment]
`cardStackView.setClickable(false);
        cardStackView.setAnimType(InfiniteCardView.ANIM_TYPE_SWITCH);
        cardStackView.setAnimInterpolator(new OvershootInterpolator(-8));
        cardStackView.setTransformerToFront(new DefaultCommonTransformer());`


Can I do it after the third line?

**Comment by BakerJQ** [comment]
yes

**Comment by AtharvaAbsolute** [comment]
![screenshot](https://user-images.githubusercontent.com/19706447/61776307-63e65b80-ae18-11e9-90de-81ff80a58814.png)
They show this error.

**Comment by BakerJQ** [comment]
oh gosh...my mistake....I'll update it

**Comment by AtharvaAbsolute** [comment]
Okay, please revert when done, I'll also update the lib. version. Thanks.

**Comment by BakerJQ** [comment]
try version 1.0.5

**Comment by AtharvaAbsolute** [comment]
Sure.

**Comment by AtharvaAbsolute** [comment]
Looks good, no errors now. I'm gonna test it. I'll revert.

**Comment by AtharvaAbsolute** [comment]
Thanks👍

**Comment by BakerJQ** [comment]
My pleasure to help

**Comment by AtharvaAbsolute** [comment]
Removed the delay and added the two statements just after findViewById
The app crashed, looks like it runs the animation before the cards are rendered.

`'java.lang.Object java.util.LinkedList.getFirst()' on a null object reference`
` cardStackView.bringCardToFront(1);`  got the error on this.

**Comment by BakerJQ** [comment]
I think I can only solve this by debug the project......

**Comment by AtharvaAbsolute** [comment]
I know what the problem is, the methods are executing before the cards are being rendered. I'll look into it. Can you take a remote connection and help me out. The library is awesome and has adapted to the requirements very well. The issue is probably on my side.

**Comment by BakerJQ** [comment]
remote connection may not available........for some extra reason in China......

**Comment by AtharvaAbsolute** [comment]
Okay, I'll try and debug, maybe it needs more optimization. I really appreciate the help and time. Thanks.
