### ISSUE TITLE
如果要循环滚动，怎么是性能消耗最低

### ISSUE THREAD

**Issue by liyanfang** [BakerJQ/InfiniteCards#20]
现在是在外部开一个定时器，循环
mCardView.bringCardToFront(1);
调用这个方法，然后查看时，特别消耗性能

**Comment by BakerJQ** [comment]
如果只是希望做一个循环展示，不需要有点击操作的话，建议直接用ViewPager+Transformer实现，mCardView.bringCardToFront是为了处理某一张卡片翻转到最前面的时候，需要改变ZIndex以实现盖住其他的，如果只是按一定的顺序改变的话，用ViewPager应该就行了

或者RecyclerView应该也可以做到

**Comment by BakerJQ** [comment]
或者RecyclerView，应该也可以做到
