### ISSUE TITLE
how to reverse the layout 

### ISSUE THREAD

**Issue by specloli** [BakerJQ/InfiniteCards#3]
how can i reverse the layout , i want put the outside card board in bottom .
in chinese ,我想把那些突出的卡片的边放到下面，应该怎么办？

**Comment by BakerJQ** [comment]
你可以自定义Transformer，可以看到默认的Transformer里有setTranslationY，这个就是根据传入的卡片参数对每张卡片进行Y方向的位置调整，你可以在这里进行操作，比如尝试把
- cardWidth * (0.02f * fromPosition - 0.02f * fraction * positionCount)前面的减号变成加号
