### ISSUE TITLE
这个可以左右滑动么？

### ISSUE THREAD

**Issue by wshx21** [BakerJQ/InfiniteCards#5]
这个可以左右滑动么？

**Comment by wshx21** [comment]
手指拖动那种

**Comment by BakerJQ** [comment]
目前暂时不可以，没有想好滑动应该是怎么交互，如果只是滑动消除，已经有很多这方面的库了，没必要再写一个，像这种切换的该怎么做滑动交互，还没想出个好点子。。。

**Comment by wshx21** [comment]
其实可不可以我自己写个手势监听左划右划，直接调用你放在最后的那个方法呢？，有就是怎么显示固定的条目数呢  固定3个或者4个（最多显示几个卡片
）

**Comment by BakerJQ** [comment]
这样的话是可以的，如果不做卡片和手势的跟随效果，只是单纯的手势触发，加个GestureDetector就行，然后直接调用切换的方法
