### ISSUE TITLE
动画效果问题

### ISSUE THREAD

**Issue by tosslife** [BakerJQ/InfiniteCards#6]
试了 设置 style 1 2 3  pre 和  next 切换动画都跟楼主gif上对不上
android 7.0 华为mate9 实测

**Comment by BakerJQ** [comment]
能否传个动图我看下？

**Comment by tosslife** [comment]
真机没法录gif.
效果就是切换的时候卡片没有过度动画，
直接闪一下两个卡片就换位置了
但是设置adapter的时候有动画
你有7.0的虚拟机吗？
不知道虚拟机会不会能复现。

**Comment by BakerJQ** [comment]
虚拟机7.0我测试过，我自己手机也是小米7.0的，我再多弄几个虚拟机试试吧。。。

**Comment by tosslife** [comment]
加下我qq，767758350 我录了手机视频录屏，发给你
