### ISSUE TITLE
请问可以固定显示的个数吗？

### ISSUE THREAD

**Issue by minmei** [BakerJQ/InfiniteCards#8]
您好，很喜欢你写的这个效果，但是有个小问题请教下：
目前是有多少图片就会显示多少个图片的堆叠效果，能不能固定只显示3个呢，或者能提供下思路吗，谢谢！

**Comment by BakerJQ** [comment]
谢谢你对作品的喜欢
卡片的数量其实是参考listview的adapter，getcount返回多少就显示多少个，如果你的意思是有一组卡片，但是只给3个卡片位置，然后在这一组里轮流切换，那没有做这方面的支持，因为这种方式的话交互方面不知道怎么弄，如果是这方面的需求，可以去搜一下“android探探卡片效果”，可能是你想要的
