### ISSUE TITLE
Front to back animation

### ISSUE THREAD

**Issue by Androneilz** [BakerJQ/InfiniteCards#9]
Hi. I would like the front-to-back animation to work exactly like the back-to-front animation. Meaning, the card at the front goes up, and over the top, to the back, with the rest of the stack moving forward (rather than swinging out to the side, as in your example).

I've played around with lots of options, but can't make this happen. Can you help please?

**Comment by BakerJQ** [comment]
You can rewrite the setStyle3() method in MainActivity, and change the setTransformerToBack into this, which is similar to DefaultTransformerToFront, but reverse the rotationX movement:

```
mCardView.setTransformerToBack(new AnimationTransformer() {
            @Override
            public void transformAnimation(View view, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {
                int positionCount = fromPosition - toPosition;
                float scale = (0.8f - 0.1f * fromPosition) + (0.1f * fraction * positionCount);
                view.setScaleX(scale);
                view.setScaleY(scale);
                view.setRotationX(fraction == 1 ? 0 : 180 * fraction);
                if (fraction < 0.5) {
                    view.setTranslationY(-cardHeight * (0.8f - scale) * 0.5f - cardWidth * 0.02f
                            * fromPosition - cardHeight * fraction);
                } else {
                    view.setTranslationY(-cardHeight * (0.8f - scale) * 0.5f - cardWidth * (0.02f *
                            fromPosition - 0.02f * fraction * positionCount) - cardHeight * (1 - fraction));
                }
            }

            @Override
            public void transformInterpolatedAnimation(View view, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {
            }
        });
```

**Comment by BakerJQ** [comment]
Below is the total view of setStyle3() method after rewrite:
![image](https://user-images.githubusercontent.com/11451739/30997921-91734980-a4fd-11e7-952e-165fc91171ce.png)

**Comment by BakerJQ** [comment]
You can test by press "change" button once and then press "next" button, which was swinging out to the side before rewrite. Hope this can help you.

**Comment by Androneilz** [comment]
Fantastic, that's perfect, thanks so much. 

Another question if it's ok: How can I alter the amount of overlap on the cards behind the front one? I'd like more of each card to be visible, so that the title of my item can be seen be the user.

**Comment by BakerJQ** [comment]
In this case, you'll need to recalculate the TranslationY in each Transformer.
If I understand your question correctly, try add the code below at the end of onCreate() method:
```
mCardView.setTransformerAnimAdd(new AnimationTransformer() {
            @Override
            public void transformAnimation(View view, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {
                fromPosition = toPosition + 1;
                int positionCount = fromPosition - toPosition;
                float scale = (0.8f - 0.1f * fromPosition) + (0.1f * fraction * positionCount);
                view.setScaleX(scale);
                view.setScaleY(scale);
                view.setTranslationY(-cardHeight * (0.8f - scale) * 0.5f - cardWidth * (0.05f *
                        fromPosition - 0.05f * fraction * positionCount));
                view.setAlpha(fraction);
            }

            @Override
            public void transformInterpolatedAnimation(View view, float fraction, int cardWidth, int cardHeight, int fromPosition, int toPosition) {

            }
        });
```

**Comment by BakerJQ** [comment]
![image](https://user-images.githubusercontent.com/11451739/31006694-54db5f34-a530-11e7-8199-5d59387d796c.png)

**Comment by Androneilz** [comment]
Unfortunately, that method isn't public, I can't compile that!

**Comment by BakerJQ** [comment]
Yes you can. But what you need to do is not to modify the code in DefaultTransformerXXX, but to customize your own AnimationTransformer and call setTransformerXXX method of the InfiniteCardView.

**Comment by Androneilz** [comment]
Thanks. I had to import the code directly into my project, and change all the default transformers. I've made a constant for the top gap, so it's now configurable.
